services:
  api:
    image: openjdk:11
    env_file: .env
    volumes:
      - .:/opt/api
    working_dir: /opt/api
    entrypoint: ["./mvnw", "spring-boot:run"]
    ports:
      - 8080:8080
  db:
    image: mysql:8
    env_file: .env
    expose:
      - 3306
